class Strings{
  static const find_your_home = "Find your next home";
  static const register_detail_text = "Register or sign in to Zillow to customize your searches and see your account details";
  static const email_address = "Email address";
  static const continue_text = "Continue";
  static const register = "Register";
  static const or = "Or";
  static const continue_with_facebook = "Continue with Facebook";
  static const continue_with_google = "Continue with Google";
  static const by_tapping_continue = "By tapping Continue, I accept";
  static const zillow_term_use = "Zillow’s Terms of Use";
  static const password = "Password";
  static const change = "CHANGE";
  static const at_least_8_char = "At least 8 characters";
  static const mix_of_letters = "Mix of letters, numbers and special characters";
  static const strenght_weak = "Password Strength : Weak";
  static const show = "SHOW";
  static const strength = "Password Strength : ";
  static const password_to_be = "Next, what would you like your password to be?";
  static const terms_of_use = "Terms of Use";
  static const do_you_know_your_home = "Do you own your home";
  static const claim_your_home = "Claim your home to track its value, see local market activity and more.";
  static const use_your_location = "Use your location";
  static const search_for_your_home = "Search for your home";
  static const search = "search";
  static const fair = "Fair";
  static const good = "Good";
  static const weak = "Weak";
}